# Makefile.wat -- Build ERRMSG.DLL and FILEDLG.DLL with Open Watcom 2.0
# Run from the project root: wmake -f Makefile.wat 2>&1 | tee compile.log
#
# Output:
#   dll\ERRMSG.DLL  dll\FILEDLG.DLL   (rebuilt DLLs)
#   lib\ERRMSG.LIB  lib\FILEDLG.LIB   (import libraries, auto-generated by wlink)
#
# NOTE: The C source files were written for 16-bit OS/2 and use APIs that do
# not exist in 32-bit OS/2.  They must be updated before compilation succeeds.
# See the "Source Porting Notes" section in README.md for the required changes.

CC = wcc386

# -bd : build DLL (enables __declspec(dllexport) and DLL init/term)
CFLAGS_ERRMSG  = -bt=os2 -bm -bd -5 -fpi -Oaxt -W3 -Isrc\ERRMSG -Ih -D_QC
CFLAGS_FILEDLG = -bt=os2 -bm -bd -5 -fpi -Oaxt -W3 -Isrc\FILEDLG -Ih -D_QC

ERRMSG_OBJS  = errmsg.obj syserr.obj pmerr.obj helperr.obj
FILEDLG_OBJS = opendlg.obj finddlg.obj savedlg.obj parse.obj static.obj buttons.obj

all: dll\ERRMSG.DLL dll\FILEDLG.DLL

# -------------------------------------------------------------------
# ERRMSG.DLL
# Must be built before FILEDLG.DLL (which links against lib\ERRMSG.LIB)
# -------------------------------------------------------------------
dll\ERRMSG.DLL: $(ERRMSG_OBJS)
	wlink system os2v2_dll name dll\ERRMSG.DLL &
	    file errmsg.obj, syserr.obj, pmerr.obj, helperr.obj &
	    export ErrMessageBox.1 &
	    export SysErrMsg.2=_SysErrMsg &
	    export SysErrCount.3=_SysErrCount &
	    export HelpMgrErrors.4=_HelpMgrErrors &
	    export HelpMgrCount.5=_HelpMgrCount &
	    export PMErrMsg.6=_PMErrMsg &
	    export PMErrCount.7=_PMErrCount &
	    option implib=lib\ERRMSG.LIB &
	    option map=dll\ERRMSG.MAP

errmsg.obj:  src\ERRMSG\errmsg.c  ; $(CC) $(CFLAGS_ERRMSG)  src\ERRMSG\errmsg.c
syserr.obj:  src\ERRMSG\syserr.c  ; $(CC) $(CFLAGS_ERRMSG)  src\ERRMSG\syserr.c
pmerr.obj:   src\ERRMSG\pmerr.c   ; $(CC) $(CFLAGS_ERRMSG)  src\ERRMSG\pmerr.c
helperr.obj: src\ERRMSG\helperr.c ; $(CC) $(CFLAGS_ERRMSG)  src\ERRMSG\helperr.c

# -------------------------------------------------------------------
# FILEDLG.DLL
# Depends on lib\ERRMSG.LIB produced by the ERRMSG.DLL step above
# -------------------------------------------------------------------
dll\FILEDLG.DLL: $(FILEDLG_OBJS) src\FILEDLG\DIALOG.RES
	wlink system os2v2_dll name dll\FILEDLG.DLL &
	    file opendlg.obj, finddlg.obj, savedlg.obj, parse.obj, static.obj, buttons.obj &
	    export FileOpenDlg.1 &
	    export FileSaveDlg.2 &
	    lib lib\ERRMSG.LIB &
	    option implib=lib\FILEDLG.LIB &
	    option map=dll\FILEDLG.MAP
	wrc -q src\FILEDLG\DIALOG.RES dll\FILEDLG.DLL

# Compile dialog resources
src\FILEDLG\DIALOG.RES: src\FILEDLG\FILEDLG.RC src\FILEDLG\DIALOG.H src\FILEDLG\DIALOG.DLG
	wrc -r -Isrc\FILEDLG -fo=src\FILEDLG\DIALOG.RES src\FILEDLG\FILEDLG.RC

opendlg.obj: src\FILEDLG\opendlg.c ; $(CC) $(CFLAGS_FILEDLG) src\FILEDLG\opendlg.c
finddlg.obj: src\FILEDLG\finddlg.c ; $(CC) $(CFLAGS_FILEDLG) src\FILEDLG\finddlg.c
savedlg.obj: src\FILEDLG\savedlg.c ; $(CC) $(CFLAGS_FILEDLG) src\FILEDLG\savedlg.c
parse.obj:   src\FILEDLG\parse.c   ; $(CC) $(CFLAGS_FILEDLG) src\FILEDLG\parse.c
static.obj:  src\FILEDLG\static.c  ; $(CC) $(CFLAGS_FILEDLG) src\FILEDLG\static.c
buttons.obj: src\FILEDLG\buttons.c ; $(CC) $(CFLAGS_FILEDLG) src\FILEDLG\buttons.c

# -------------------------------------------------------------------
clean: .symbolic
	@if exist *.obj           del *.obj
	@if exist src\FILEDLG\DIALOG.RES  del src\FILEDLG\DIALOG.RES
	@if exist dll\ERRMSG.DLL  del dll\ERRMSG.DLL
	@if exist dll\FILEDLG.DLL del dll\FILEDLG.DLL
	@if exist dll\ERRMSG.MAP  del dll\ERRMSG.MAP
	@if exist dll\FILEDLG.MAP del dll\FILEDLG.MAP
	@if exist lib\ERRMSG.LIB  del lib\ERRMSG.LIB
	@if exist lib\FILEDLG.LIB del lib\FILEDLG.LIB
	@if exist compile.log     del compile.log
