/****************************************************************************
 * ERRCONST.H                                                               *
 *                                                                          *
 *  This file contains the declarations of the string constants used in     *
 *  the standard system error handler.                                      *
 *                                                                          *
 *  Modifications --                                                        *
 *      09-Oct-1989 : Initial version.                                      *
 ****************************************************************************/

    extern CHAR     szUnkSysError[];
    extern CHAR     szUnkAppError[];
